babel用及びes6用に書き換えました
shisoAqron/ooba-bot pull request #2
Opened 2017-08-24 09:52 UTC by shisoAqron

@taiju59 
既存botの.eslintrcと.babelrcに対応した書き方をしました。
変換して動作することを確認しています。
line送信部分は明日モジュールとして切り分ける予定です。

2017-08-24 11:15 UTC, taiju59 requested changes
早速es6っぽい書き方がされていていいですね:+1::+1:

これは完全にこっちの都合なんですが、ブランチ名に日本語は使用しないようにお願いします。  
gitlabでこれをするとリポジトリが修復不可能な感じに破壊されてしまう、という謎現象が発生するので

2017-08-24 11:15 UTC, taiju59 commented on src/index.js
> +app.listen(port, ()=> {
これは好みの問題且つeslintrcで設定したいところなんですが、  
`=>` の前にはスペースを空けておいてください

2017-08-25 01:03 UTC, shisoAqron commented
@taiju59 
アローの前にスペースを入れる修正をしました。

2017-08-25 01:31 UTC, taiju59 commented
@shisoAqron  
完璧な対応ありがとうございます！  
確認したのでマージします 🙆‍♂️

2017-08-25 01:31 UTC, merged